### ISSUE TITLE
We should use buffered chans.

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#128]
We should use buffered chans.

_Originally posted by @adrielp in https://github.com/liatrio/liatrio-otel-collector/pull/123#discussion_r1335243292_

**Comment by jburns24** [comment]
I think this is already done https://github.com/search?q=repo%3Aliatrio%2Fliatrio-otel-collector+%22chan+%22&type=code

**Comment by adrielp** [comment]
yup, this was a duplicate and the other one didn't look to get closed. thanks for catching this!
