### ISSUE TITLE
test: provider receiver `config.go`

### ISSUE THREAD

**Issue by nsshaddox** [liatrio/liatrio-otel-collector#131]
Adding tests for /liatrio-otel-collector/pkg/receiver/gitproviderreceiver/config.go

There are a few tests already but there aren't any for the Unmarshal functions.

**Comment by adrielp** [comment]
Let's add scraper errors and some test cases to loaded config like this example: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/config_test.go
