### ISSUE TITLE
Add more test cases when unmarshalling config in the git provider receiver

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#145]
We should add some additional test cases here. Let's merge this in and iterate on another  tasks to add more test cases.

_Originally posted by @adrielp in https://github.com/liatrio/liatrio-otel-collector/pull/144#discussion_r1354978080_

**Comment by rafiramadhana** [comment]
@adrielp can I work on this? thanks

**Comment by nsshaddox** [comment]
reference file: `github.com/liatrio/liatrio-otel-collector/pkg/receiver/gitproviderreceiver`

**Comment by adrielp** [comment]
> @adrielp can I work on this? thanks

Sure! Appreciate the willingness to contribute 😊

**Comment by adrielp** [comment]
Closing this. We've added bunches of tests iteratively as we developed so this specific task isn't needed.
