### ISSUE TITLE
graphql generated files in scrapers should be converted to match naming convention

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#173]
i didn't know what this file was at first. i'd like to see it be consistent with the file in the github scraper folder. named `generated-graphql.go`. 

The way that is changed is by updated the graphql yaml & regenerating the code.

_Originally posted by @adrielp in https://github.com/liatrio/liatrio-otel-collector/pull/172#discussion_r1373477532_

**Comment by jburns24** [comment]
Addressed in https://github.com/liatrio/liatrio-otel-collector/tree/cleanup
