### ISSUE TITLE
Contribute 3rd PR for git provider receiver

### ISSUE THREAD

**Issue by 4lch4** [liatrio/liatrio-otel-collector#214]
# Overview

Now that we've finished the 2nd contribution downstream, we're ready to contribute more of the metrics we gather from GitHub.

In the interest of smaller PRs, we'll have a limited amount of metrics but the third PR needs to contain the following metrics:

- [x] `git.repository.pull_request.open.count`
- [x] `git.repository.pull_request.open.time`
- [x] `git.repository.pull_request.merged.count`
- [x] `git.repository.pull_request.merge.time`
- [x] `git.repository.pull_request.approval.time`
- [x] `git.repository.pull_request.deployment.time`

**Comment by 4lch4** [comment]
After talking to @adrielp, I updated the metrics we intend to add.

**Comment by 4lch4** [comment]
Added two remaining PR metrics to list.

**Comment by 4lch4** [comment]
After a lot of iterating, I've submitted the PR:

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29642

**Comment by 4lch4** [comment]
We're still pending a merge approval. After a lot of improvements were made and we were brought up to snuff, we were given a ready-to-merge label, but that's when a build on Windows failed due to an issue unrelated to us. They've since fixed that issue so we updated our PR, got an approval for the workflows, and now it's failing for _another_ issue.

I will look into this issue and figure out what's going on to get this merged.

**Comment by adrielp** [comment]
If this isn't merged in by wednesday I'll bring it up in the collector sig.

**Comment by adrielp** [comment]
Did not bring up to collector SIG directly. It was viewed again in the weekly report. There are merge conflicts. I will be reaching out in the community slack to address some things and see if there's no issue with directly fixing them.

**Comment by adrielp** [comment]
Rebased, fixed, and just now waiting for maintainers to merge. made the callout & ask again.

**Comment by adrielp** [comment]
DONE
