### ISSUE TITLE
Move back to renovatebot and remove dependabot

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#225]
# Overview

Dependabot continues to be subpar. The only reason we originally enabled it was to match what was in the OTEL project. OTEL has finally moved away from dependabot, and the time is ripe to move back to Renovate.

**Comment by densellp** [comment]
I can look into this

**Comment by densellp** [comment]
Renovate made a PR to merge into main, but 11 Pull Request will be created to fix dependancies in the project

**Comment by densellp** [comment]
PR is open for review
