### ISSUE TITLE
Re-figure out and document the use of pkg golden generation as part of adding new metrics and tests

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#259]
# Overview

Once upon a time, we use the OpenTelemetry [golden package](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/pkg/golden/v0.92.0/pkg/golden/golden.go#L40) to generate the [happy path and no repos](https://github.com/liatrio/liatrio-otel-collector/tree/main/receiver/gitproviderreceiver/internal/scraper/githubscraper/testdata/scraper) expected metrics files. 

The goal of this ticket is to document how we used it as part of contributing (light mention in CONTRIBUTING.md and strong mention/instructions in README.md for the gitproviderreceiver) so that as new metrics get added, or changed, it's clear on how to re-generate or update those files and the corresponding tests to ensure accurate coverage.

**Comment by adrielp** [comment]
cc. @nsshaddox  if you have any insight. I think you originally did the work alongside @rhoofard

**Comment by adrielp** [comment]
This should be about done because of @caseyw 's PR that is related.

**Comment by caseyw** [comment]
Here's the changes that were approved/merged:
https://github.com/liatrio/liatrio-otel-collector/tree/main/receiver/gitproviderreceiver#updating-tests

**Comment by adrielp** [comment]
Adriel, will review today.
