### ISSUE TITLE
Investigate how renovate can or can't handle golang multimodule monorepos

### ISSUE THREAD

**Issue by acramsay** [liatrio/liatrio-otel-collector#279]
The [Liatrio Otel Collector](https://github.com/liatrio/liatrio-otel-collector/) repo is a good example of the problem. When renovate make certain updates to a dependent go.mod file (e.g. for the gitprovider receiver), it will _not_ also update other go.mod files contained in the same repo. Thus, Renovate needs to run again to complete the needed changes.

Running `make tidy-all` should solve this but requires hosting our own instance of Renovate.. Can Renovate handle this better natively?

**Comment by acramsay** [comment]
Does renovate have a setting to run all of it's rules repeatedly until is stops making code changes and then make a single commit?

**Comment by adrielp** [comment]
This can be fixed with a post task when self-hosting renovatebot. When we self-host renovatebot we can support this. For now I will close as wont do as I did a lot of Renovate config to group deps together and will continue to iterate.
