### ISSUE TITLE
Contribute a developer experience improvement to OTEL via the OTEL issue

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#31]
# Overview

There are a few things in the OTEL contrib local developer experience that could be improved when developing a new component. An issue has been opened on the project [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24241)

## Acceptance Criteria
* the issue is assigned
* the pr is approved and merge
* docs are updated accordingly to reflect the improvement
* a blog post is made

**Comment by MisterC500** [comment]
PR - https://github.com/liatrio/liatrio-otel-collector/pull/117 addressing comments

**Comment by adrielp** [comment]
Closing this out & creating additional work for others to pick up.
