### ISSUE TITLE
Automate the running of a new or existing tool that diffs the GitProviderReceiver code between the liatrio-otel-collector and otel-collector-contrib repos

### ISSUE THREAD

**Issue by acramsay** [liatrio/liatrio-otel-collector#350]
We manually sync code changes between the [liatrio-otel-collector](https://github.com/liatrio/liatrio-otel-collector/tree/main/receiver/gitproviderreceiver) and [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/gitproviderreceiver) repos. We don't currently know of a good way to automate this process. Instead, we should build and/or implement a tool to diff the code bases regularly.

Note that these two repos are _not_ forks and we should not diff commits.

**Comment by adrielp** [comment]
The more and more I think about this, I don't think it's necessary and should be done by a human making a decision. Happy to re-evaluate if this becomes something painful and urgent. But for now, I'm going to close this as wont do.
