### ISSUE TITLE
Update o11y to address signals for "Build In Security"

### ISSUE THREAD

**Issue by ericchapman80** [liatrio/liatrio-otel-collector#367]

**Comment by ericchapman80** [comment]
Trend for the number of open vulnerabilities over time (Critical & High)
MTTR on Critical and High - Identified to remediated
Target Goals:
Critical should be resolved in ~ 14 days
High should be resolved in 30 - 45 days.
Date of discovery of CVE not date of identified by SAST tool
Fixed vs opened - looking for the ratios of issues remediated
Running summary from the last 30 days (for example):
Fixed vulnerabilities
Newly reported vulnerabilities
Ignored (what the team is choosing not to remediate)

**Comment by adrielp** [comment]
turn this into a milestone

**Comment by adrielp** [comment]
This has been turned into a milestone
