### ISSUE TITLE
Add codecov as a workflow & badge to the liatrio-otel-collector

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#38]
# Overview

The otel collector repo needs to have a codecov & codeql badges & workflows, helping us set a target of test coverage & displaying this coverage to the users. 

## Acceptance Criteria
* a workflow is added for codecov that runs after unit tests
* a badge is updated in the readme showing the codecov status
* a codeql badge is added and formatted the same as the other badges

### Examples: 

Below are some great examples from the opentelemetry contrib repository.
https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-collector-contrib%20codecov&type=code

**Comment by nsshaddox** [comment]
Progress:
- [X] a workflow is added for codecov that runs after unit tests
- [X] a badge is updated in the readme showing the codecov status
- [/] a codeql badge is added and formatted the same as the other badges (Can't figure out how to format)
