### ISSUE TITLE
Fix the release of the otel collector to enable importing by version of module packages

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#408]
# Overview 

To build a custom collector from outside of the Liatrio OTEL Collector means you have to import the package with a version specified like `v0.0.0-<hash>`. This is because the version of the package internally doesn't get edited with the release on main.

The OpenTelemetry release cycle is a bi-weekly cycle where releases are cut from an external repository which edits the files according to the new release version.

We should fix this such that:
* release is triggered and edits the files with the next version
* files are committed (automation) 
* files are released from said version

**Comment by jburns24** [comment]
Talked about this issue with Adriel from a high level my understanding is the task is to modify the release workflow on merge to main such that it

1. calculates the next semvar 
2. runs multimod with the next semvar
3. commits the changed files (with a chore tag)
4. run goreleaser to build and publish

**Comment by gnmeyer** [comment]
#457

**Comment by adrielp** [comment]
So was able to get multimod to work after some troubleshooting. There's still some issues though that have to be fixed. 

1. pkg.go.dev doesn't detect the version because semantic release cuts against originating version, and doesn't include the commits made in the workflow. 
2. Some slowness around the pipeline. Implemented a caching PR but it's actually slower. There's some potential restructuring we can do to make things a little faster.

Happy to sync up on this. I thought there was another thing but I did sleep over the weekend so not recalling right now.

**Comment by jburns24** [comment]
Current issue is that go-semantic-release tagged the sha that triggered the workflow instead of the commit made my multimod

I think the path forward is:
* move go-semantic-release to a new workflow
    * get gh token from app and use for making semeantic release
* jobs in workflows that trigger on pushes to main dont trigger if we are the bot `if: github.actor != '<bot name>'`
* semantic release workflow is triggered:
```on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
 ```

From [this](https://liatrio.slack.com/archives/C04KGSFF407/p1724105959083639?thread_ts=1724103631.747519&cid=C04KGSFF407) conversation

**Comment by jburns24** [comment]
Once we validate in pkg.go.dev is updated and 'build-and-test- does not run twice in a row let's call this done.

**Comment by adrielp** [comment]
TODO: (can be done under a separate ticket)
* update the create release workflow to have a better changelog, the fix made the changelog suck
* perf improvements
* propose changes to multimod (maybe)

After changes & iterations, pkg.go.dev and things now correctly work.

**Comment by jburns24** [comment]
Changelog refinement done in [#477](https://github.com/liatrio/liatrio-otel-collector/issues/477)
