### ISSUE TITLE
Create Networking Policy to allow traffic within tag-0lly namespaces due to the introduction of policies by the K8s team

### ISSUE THREAD

**Issue by MorganCloud** [liatrio/liatrio-otel-collector#447]
Currently the networking plugin the k8s teams are using isn’t configured to enforce network policy rules. But they will in the future and when they do, current network policies maybe rendered somewhat ineffective.

:warning: Therefore, if your application is currently deploying network policies these policies may suddenly cause your application to break if these policies don’t have the desired effect.

Our network policies and namespaces are  below, so we need to identify any traffic that is necessary but not explicit in the network policies and apply them to the appropriate namespaces:

```
NetworkPolicy | Namespace | Type 

allow-cluster-ingress | otel-gateway | Ingress 

allow-delivery-cluster-ingress | tag-o11y-loki | Ingress 

allow-delivery-cluster-ingress | otel-delivery | Ingress 

allow-loki-access | tag-o11y-loki | Ingress 

```

**Comment by jburns24** [comment]
https://github.com/liatrio/tag-o11y-manifests/pull/100
