### ISSUE TITLE
Create a reusable workflow that gets a Dex token

### ISSUE THREAD

**Issue by jburns24** [liatrio/liatrio-otel-collector#476]
https://github.com/liatrio/k8s-platform-v3-monorepo/actions/workflows/dex-testing.yml

This workflow shows how to exchange a GitHub token for a 
Dex token. At time of writing the Dex token you get from this
will not be able to authenticate with the cluster. Kpv3 team 
needs to add some OPA to Dex so that it pulls the identity
of the workflow (believe this will be something like repo:liatrio-
otel-collector:/ref/head/main) out and puts it in the Dex 
'email' token field

Once Dex is updated to put the workflow 
identity in the Dex token we can (or kpv3 
will) add RBAC to the cluster so that we 
can assume some roles when that email 
comes in. 

Update kpv3-cli to support this token exchange. Really it 
seems like it is the same post request that curl does but it 
should read in an existing Github token

https://github.com/liatrio/k8s-platform-v3-monorepo/blob/main/tooling/kpv3-cli/cmd/auth.go

### To Do

- [ ] Create reusable workflow like dex-testing.yml to get a feel for this flow
- [ ] Update kpv3-cli to exchange a GitHub token for a Dex token
- [ ] Update reusable workflow to get GitHub token and then using kpv3-cli exchange that for a Dex token

### Questions
Is a reusable workflow the right thing here? Can we export a secret?

**Comment by jburns24** [comment]
Pausing work on this to spike on the OpenTelemetry Operator v1beta1 migration.

**Comment by adrielp** [comment]
Closing this as @blairdrummond I believe has created a reusable workflow thus this particular issue isn't needed.
