### ISSUE TITLE
Add missing unit tests for the github scraper

### ISSUE THREAD

**Issue by amber-beasley-liatrio** [liatrio/liatrio-otel-collector#50]
There is no unit testing in 6 functions (at the time of writing this issue) in the `github_scraper.go` file and 0 unit tests in the `github_scraper_test.go`

* [ ] write unit tests for each

**Comment by densellp** [comment]
I will be looking at this today and see what direction I need to GO to test this

**Comment by adrielp** [comment]
Closing this in favor of smaller batched testing
