### ISSUE TITLE
chore: improve error catching of login query

### ISSUE THREAD

**Issue by amber-beasley-liatrio** [liatrio/liatrio-otel-collector#51]
The `login_query` in the `github_scraper.go` file is used to check if the provided `org` in the config.yml file is an org or a user. Currently if the provided config is a user, an error is caught from the query and an info message logged.

It would be better to check after getting an error on the login query against an org, if a query against a user produces an error. If an error returns on user query, then we should log an error to indicate that the config provided cannot be found at all. 

* [ ] move this logic to its own function, with the return result being a boolean if the org provided in the `config.yml` is an organization or user
* [ ] convert `login_query` to `org_login_query`
* [ ] add another login query but for users
```go
	var user_login_query struct {
		Organization struct {
			Login githubv4.String
		} `graphql:"user(login: $login)"`
	}
```
* [ ] add additional if else statements to catch the error when an org its found, then check if user can be found, and if that errors, log the error. If user can be found, set `provided_org_is_org` to false
> that section might look something like this

```go
	// do we get an error when looking up the provided org config as an org?
	err_org := graphqlClient.Query(context.Background(), &org_login_query, variables)
	if err_org != nil {
		ghs.logger.Sugar().Info("Org provided not found; it may be a user")
		// do we get an error when looking up the provided org config as a user?
		err_user := graphqlClient.Query(context.Background(), &user_login_query, variables)
		if err_user != nil {
			// if we get here, we got an error trying to look up the provided org config as an org and user
			ghs.logger.Sugar().Errorf("Error finding Org config provided, not found as org or user", zap.Error(err_user))
		} else {
			// no error found when looking up provided org config as a user
			provided_org_is_org = false
		}
	} else {
		// no error found when looking up provided org config as an org
		provided_org_is_org = true
	}
	// now that we have determined if login is org or user, we can define the query
```

**Comment by adrielp** [comment]
@amber-beasley-liatrio , I think [this pull request](https://github.com/liatrio/liatrio-otel-collector/pull/66) for the refactor succesfully meats the criteria on this issue. Please review the PR and let me know if you agree.

The specific aspect of the login code error handling can be found in the following:
* this is the [login graphql query](https://github.com/liatrio/liatrio-otel-collector/blob/col-genqlient-1/pkg/receiver/gitproviderreceiver/internal/scraper/githubscraper/genqlient.graphql#L59-L66)
* this [block here](https://github.com/liatrio/liatrio-otel-collector/blob/col-genqlient-1/pkg/receiver/gitproviderreceiver/internal/scraper/githubscraper/github_scraper.go#L286-L302) checks the type and if the user exists. if it doesn't then it'll emit no metrics and throw an error, stopping the scrape function from continuing
* [these are the two functions](https://github.com/liatrio/liatrio-otel-collector/blob/col-genqlient-1/pkg/receiver/gitproviderreceiver/internal/scraper/githubscraper/graphql_helpers.go#L92-L121) being called that check those things

**Comment by amber-beasley-liatrio** [comment]
Yep! Totally covers #51
