### ISSUE TITLE
Organization attributes in metrics 

### ISSUE THREAD

**Issue by pmpaulino** [liatrio/liatrio-otel-collector#57]
I would expect to be able to filter metrics via an organization or individual attribute for the use case where more than one org or individual is being collected from Git Hub or other git providers.

**Comment by adrielp** [comment]
Why can't you source based on attributes now?

**Comment by pmpaulino** [comment]
You can see all the attributes in this example screenshot. 
![image](https://github.com/liatrio/liatrio-otel-collector/assets/21304538/e2b352ea-819a-48cc-a505-1a60958fd435)

**Comment by adrielp** [comment]
Do I recall correctly that in the evening yesterday you fixed this in the demo?
