### ISSUE TITLE
Panic in git provider

### ISSUE THREAD

**Issue by pmpaulino** [liatrio/liatrio-otel-collector#59]
I'm seeing a panic after about 20-25 minutes when running the collector against about 100 repos.

**Comment by adrielp** [comment]
I think we might've fixed it, but not entirely sure. Still testing

**Comment by adrielp** [comment]
Fixed this in the latest version `v0.7.1`. An index out of range error was causing a panic when trying to calculate the branch age because there are some repositories that have branches without any commits on them. We chose to zero these out.
