### ISSUE TITLE
Add ability to search within the organization to prune down information

### ISSUE THREAD

**Issue by adrielp** [liatrio/liatrio-otel-collector#68]
# Overview
 
With large orgs there's the potential for not being able to actually grab all the data. For example, we've seen some orgs with 15,000+ repositories. Thus it'd be performant and ideal to be able to additionally prune down the search in those cases, such that you can search for the things you want. 

## Acceptance Criteria
* tested
* documentation updated
* configuration optional
* allows for searching by topic, team, or repo name

**Comment by amber-beasley-aa** [comment]
I saw the old sdc had a team config file that let you list repos to include. Maybe adding a list of repos might be another good option in addition to search by topic, team, or repo name? (this could totally be another issue/feature ask)

**Comment by adrielp** [comment]
Pull request has been merged to provide said functionality.
