### ISSUE TITLE
Add pull request approval time metric to the gitlab scraper

### ISSUE THREAD

**Issue by 4lch4** [liatrio/liatrio-otel-collector#95]
# Overview

Add the pull request approval time metric to the gitlab scraper.

## AC

- [ ] Docs updated.
- [ ] Scraper is tested.
- [ ] Any added functions are tested.

**Comment by rhoofard** [comment]
Doesn't look like approval time is something we can grab from either the graphql or rest api.  They just make the distinction on whether something is approved or not

**Comment by adrielp** [comment]
Let's evaluate this one.

**Comment by adrielp** [comment]
Closing this for now as it doesn't appear to be available in the GitLab API.
